#cloud-config
package_update: true
packages: [docker.io, git]
runcmd:
  - systemctl enable --now docker
  - git clone https://github.com/acme/blackbox-lcs /opt/lcs
  - cd /opt/lcs && docker build -t lcs:blackbox .
  - docker run -d --name lcs --restart=always \
      --read-only --tmpfs /tmp --network none \
      -v /dev/shm:/dev/shm lcs:blackbox
