name: Vue Deploy
on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发部署

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11'

      # 3. 安装依赖
      - name: Install dependencies
        run: npm install

      # 4. 构建项目
      - name: Build project
        run: npm run build

      # 5. 通过 SCP 将构建产物上传到服务器
      -  name: Transfer files via SCP[ty-n]  uses: appleboy/scp-action@v0.1.7[ty-n]  with:[ty-n]    host: $</LaTex>{{ secrets.SSH_HOST }}
    username: <LaTex>${{ secrets.SSH\_USERNAME }}[ty-n]    key: $</LaTex>{{ secrets.SSH_PRIVATE_KEY }}
    source: "dist/"  # 确认源文件路径
    target: "/path/to/target"  # 确认目标路径
